[package]
name = "rsxui-website"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
axum.workspace = true
tokio.workspace = true
rsx = { path = "../rsx" }
rsxui = { path = "../rsxui" }
tower-http = { version = "0.6.8", features = ["fs"] }
